# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f810dc4309b55e23a56912d896d2c02343d97a329a59a2c3d40c3aaca6d41bfe96f6f2b81d17a21e469f14b08347eec44672aff939213a7ed453931825fda4

test:
  secret_key_base: 5036b3808523021ca23f4e6ea82eb8b11f9f4d0a558aecfcd4bb0452ec9090046b17e24356edabf020d5b8ac3e698defa4bc90224956dc0a95a02e9ac484f46f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
